services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123456qwe
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:     